apiVersion: v1
kind: Namespace
metadata:
  name: test-pod-bandwidth4
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.25
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.25
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.25
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod4
  namespace: test-pod-bandwidth4
  annotations:
    kubernetes.io/ingress-bandwidth: "1M"
    kubernetes.io/egress-bandwidth: "1M"
spec:
  containers:
    - name: test-container
      image: alpine:3.18  # <-- Change to Alpine
      command: ['sh', '-c', 'apk add --no-cache iperf3 && sleep 3600']