name: Create Patch Validation Test Run
on:
  workflow_dispatch:
    inputs:
      rcs:
        description: 'Provide the list of RCs (comma separated)'
        required: true
        default: 'v1.29.0-rc1,v1.30.0-rc1,v1.31.0-rc1,v1.32.0-rc1'

permissions:
  contents: read

jobs:
  create_qase_run:
    name: 'Create Qase Run'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout distros
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Permission for script
        run: chmod +x ./scripts/qase-patch-validation.sh

      - name: Qase Run Script
        shell: bash
        env:
          RCS: ${{ github.event.inputs.rcs }}
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
        run:  ./scripts/qase-patch-validation.sh

